# Generated by Django 2.1.15 on 2020-05-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='profile_picture'),
        ),
    ]
