# Generated by Django 2.1.15 on 2020-06-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_document_privatedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.CharField(blank=True, choices=[('文科1類', '文科1類'), ('文科2類', '文科2類'), ('文科3類', '文科3類'), ('理科1類', '理科1類'), ('理科2類', '理科2類'), ('理科3類', '理科3類')], max_length=10, verbose_name='division'),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('前期教養学部', '前期教養学部'), ('後期教養学部', '後期教養学部'), ('法学部', '法学部'), ('経済学部', '経済学部'), ('文学部', '文学部'), ('教育学部', '教育学部'), ('理学部', '理学部'), ('工学部', '工学部'), ('農学部', '農学部'), ('薬学部', '薬学部'), ('医学部', '医学部')], max_length=10, verbose_name='faculty'),
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.CharField(blank=True, choices=[('1年', '1年'), ('2年', '2年'), ('3年', '3年'), ('4年', '4年')], max_length=10, verbose_name='grade'),
        ),
    ]
