# Generated by Django 2.1.15 on 2020-05-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_auto_20200516_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_thread',
            field=models.ManyToManyField(blank=True, to='cms.Thread', verbose_name='お気に入りスレッド'),
        ),
    ]
