# Generated by Django 2.1.15 on 2020-05-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_image_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
