# Generated by Django 2.1.15 on 2020-05-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_delete_photo'),
        ('cms', '0007_user_favorite_thread'),
    ]

    operations = [
    ]
