# Generated by Django 2.1.15 on 2020-05-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20200517_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='faculty',
            field=models.IntegerField(choices=[(1, '前期教養学部'), (2, '後期教養学部'), (3, '法学部'), (4, '経済学部'), (5, '文学部'), (6, '教育学部'), (7, '理学部'), (8, '工学部'), (9, '農学部'), (10, '薬学部'), (11, '医学部')], null=True),
        ),
    ]
