# Generated by Django 2.1.15 on 2020-05-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_auto_20200518_1822'),
        ('cms', '0011_user_profile_picture'),
    ]

    operations = [
    ]
